### ISSUE TITLE
Available for mouse datasets?

### ISSUE THREAD

**Issue by multitalk** [SrivastavaLab-ICL/PPMS#1]
This is a fantastic tool. I just want to know if PPMS can be used for mouse datasets because I noticed that there are only human genome references in the released files. Thanks in advance.

**Comment by pksrivas** [comment]
Thanks, Xin, the framework will work for the mouse dataset as well. The only limiting factor is the annotation of primary microRNAs in the genome.

Best Wishes,

Prashant

**Comment by multitalk** [comment]
Cool, thank you very much, Prashant. I look forward to the update!
